-- Local development seed data only. Never run against a production
-- project. See docs/DATABASE.md "Local development".

insert into public.retailers
  (legal_name, display_name, slug, status, tier, default_currency, default_locale)
values
  ('Atelier Demo, Inc.', 'Atelier Demo', 'atelier-demo', 'active', 'house', 'USD', 'en-US')
on conflict (slug) do nothing;

-- 44 possen.com fabrics added to Atelier Demo's Suits/Jackets catalogue.
-- Images: shared nebelspiegel.com catalogue photography (same CDN the
-- founder's own template already uses -- see paon-template.html route.ts's
-- usesSharedCataloguePhotography / suitOrJacketFromImageId, which buckets
-- by the 4-digit id in the image path: <8000 = Suits, >=8000 = Jackets.
insert into public.products (retailer_id, name, slug, description, status, is_made_to_order, primary_image_url, swatch_image_url)
values
  ((select id from public.retailers where slug = 'atelier-demo'), 'Greige Cotton Corduroy', 'greige-cotton-corduroy-6090', 'Greige Cotton Corduroy from Pontoglio. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6090.jpg', 'https://www.nebelspiegel.com/images/6090_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Bone Wool Blend Twill', 'bone-wool-blend-twill-6091', 'Bone Wool Blend Twill from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6091.jpg', 'https://www.nebelspiegel.com/images/6091_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Ivory-taupe Wool Glencheck', 'ivory-taupe-wool-glencheck-6092', 'Ivory-taupe Wool Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6092.jpg', 'https://www.nebelspiegel.com/images/6092_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Cedar Brown Silk, Wool & Cashmere Glencheck', 'cedar-brown-silk-wool-cashmere-glencheck-6093', 'Cedar Brown Silk, Wool & Cashmere Glencheck from Zegna. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6093.jpg', 'https://www.nebelspiegel.com/images/6093_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Chocolate Brown Wool Twill', 'chocolate-brown-wool-twill-6095', 'Chocolate Brown Wool Twill from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6095.jpg', 'https://www.nebelspiegel.com/images/6095_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Dark Brown Wool-silk-linen Glencheck', 'dark-brown-wool-silk-linen-glencheck-6096', 'Dark Brown Wool-silk-linen Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6096.jpg', 'https://www.nebelspiegel.com/images/6096_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Mauve Cotton Corduroy', 'mauve-cotton-corduroy-6097', 'Mauve Cotton Corduroy from Pontoglio. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6097.jpg', 'https://www.nebelspiegel.com/images/6097_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Pale Pink Alpaca-wool Blend White Pin Stripes', 'pale-pink-alpaca-wool-blend-white-pin-stripes-6098', 'Pale Pink Alpaca-wool Blend White Pin Stripes from Ferla. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6098.jpg', 'https://www.nebelspiegel.com/images/6098_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Dusty Pink & Dark Brown Silk, Wool & Cashmere Glencheck', 'dusty-pink-dark-brown-silk-wool-cashmere-glencheck-6099', 'Dusty Pink & Dark Brown Silk, Wool & Cashmere Glencheck from Zegna. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6099.jpg', 'https://www.nebelspiegel.com/images/6099_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Light Blue Wool Blend Twill', 'light-blue-wool-blend-twill-6100', 'Light Blue Wool Blend Twill from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6100.jpg', 'https://www.nebelspiegel.com/images/6100_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Dark Blue-midnight Blue Wool Glencheck', 'dark-blue-midnight-blue-wool-glencheck-6101', 'Dark Blue-midnight Blue Wool Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6101.jpg', 'https://www.nebelspiegel.com/images/6101_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Indigo Blue Wool Twill', 'indigo-blue-wool-twill-6102', 'Indigo Blue Wool Twill from Reda. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6102.jpg', 'https://www.nebelspiegel.com/images/6102_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Midnight Blue Wool Twill', 'midnight-blue-wool-twill-6103', 'Midnight Blue Wool Twill from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6103.jpg', 'https://www.nebelspiegel.com/images/6103_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Prussian Blue Cotton Corduroy', 'prussian-blue-cotton-corduroy-6104', 'Prussian Blue Cotton Corduroy from Pontoglio. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6104.jpg', 'https://www.nebelspiegel.com/images/6104_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Petrol-midnight Blue Wool Micro-effect', 'petrol-midnight-blue-wool-micro-effect-6105', 'Petrol-midnight Blue Wool Micro-effect from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6105.jpg', 'https://www.nebelspiegel.com/images/6105_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Storm Blue Silk, Wool & Cashmere Glencheck', 'storm-blue-silk-wool-cashmere-glencheck-6106', 'Storm Blue Silk, Wool & Cashmere Glencheck from Zegna. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6106.jpg', 'https://www.nebelspiegel.com/images/6106_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Teal Cotton Corduroy', 'teal-cotton-corduroy-6107', 'Teal Cotton Corduroy from Pontoglio. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6107.jpg', 'https://www.nebelspiegel.com/images/6107_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Petrol Wool Blend Twill', 'petrol-wool-blend-twill-6108', 'Petrol Wool Blend Twill from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6108.jpg', 'https://www.nebelspiegel.com/images/6108_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Black-white Wool Glencheck', 'black-white-wool-glencheck-6109', 'Black-white Wool Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/6109.jpg', 'https://www.nebelspiegel.com/images/6109_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Ivory Wool-silk Herringbone', 'ivory-wool-silk-herringbone-9209', 'Ivory Wool-silk Herringbone from Drago. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9209.jpg', 'https://www.nebelspiegel.com/images/9209_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Sand Wool-silk Panama', 'sand-wool-silk-panama-9210', 'Sand Wool-silk Panama from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9210.jpg', 'https://www.nebelspiegel.com/images/9210_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Bone S190 Wool Beaver Look', 'bone-s190-wool-beaver-look-9211', 'Bone S190 Wool Beaver Look from Zegna. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9211.jpg', 'https://www.nebelspiegel.com/images/9211_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Ivory-l.brown Wool-silk Glencheck', 'ivory-l-brown-wool-silk-glencheck-9212', 'Ivory-l.brown Wool-silk Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9212.jpg', 'https://www.nebelspiegel.com/images/9212_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Beige Wool-silk Basketweave', 'beige-wool-silk-basketweave-9213', 'Beige Wool-silk Basketweave from Drago. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9213.jpg', 'https://www.nebelspiegel.com/images/9213_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Ivory-taupe Wool-silk-cashmere Glencheck', 'ivory-taupe-wool-silk-cashmere-glencheck-9215', 'Ivory-taupe Wool-silk-cashmere Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9215.jpg', 'https://www.nebelspiegel.com/images/9215_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Mocha S190 Wool Beaver Look', 'mocha-s190-wool-beaver-look-9216', 'Mocha S190 Wool Beaver Look from Zegna. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9216.jpg', 'https://www.nebelspiegel.com/images/9216_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Coffee Brown Wool-silk Panama', 'coffee-brown-wool-silk-panama-9217', 'Coffee Brown Wool-silk Panama from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9217.jpg', 'https://www.nebelspiegel.com/images/9217_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Dark Brown-midnight Blue Wool-silk Glencheck', 'dark-brown-midnight-blue-wool-silk-glencheck-9218', 'Dark Brown-midnight Blue Wool-silk Glencheck from Drago. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9218.jpg', 'https://www.nebelspiegel.com/images/9218_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Cognac Wool-silk Panama', 'cognac-wool-silk-panama-9219', 'Cognac Wool-silk Panama from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9219.jpg', 'https://www.nebelspiegel.com/images/9219_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Light Amber Wool-silk-linen Sharkskin', 'light-amber-wool-silk-linen-sharkskin-9220', 'Light Amber Wool-silk-linen Sharkskin from Delfino. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9220.jpg', 'https://www.nebelspiegel.com/images/9220_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Copper-l.amber Wool-silk Glencheck', 'copper-l-amber-wool-silk-glencheck-9221', 'Copper-l.amber Wool-silk Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9221.jpg', 'https://www.nebelspiegel.com/images/9221_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Maroon-ivory Wool-alpaca Blend Houndstooth', 'maroon-ivory-wool-alpaca-blend-houndstooth-9222', 'Maroon-ivory Wool-alpaca Blend Houndstooth from Ferla. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9222.jpg', 'https://www.nebelspiegel.com/images/9222_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Wine Red Wool-silk Panama', 'wine-red-wool-silk-panama-9223', 'Wine Red Wool-silk Panama from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9223.jpg', 'https://www.nebelspiegel.com/images/9223_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Dusty Pink-maroon Wool-silk Glencheck', 'dusty-pink-maroon-wool-silk-glencheck-9224', 'Dusty Pink-maroon Wool-silk Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9224.jpg', 'https://www.nebelspiegel.com/images/9224_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Purple Wool-silk-linen Sharkskin', 'purple-wool-silk-linen-sharkskin-9225', 'Purple Wool-silk-linen Sharkskin from Delfino. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9225.jpg', 'https://www.nebelspiegel.com/images/9225_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Neapolitan Blue Wool-silk-cashmere Glencheck', 'neapolitan-blue-wool-silk-cashmere-glencheck-9226', 'Neapolitan Blue Wool-silk-cashmere Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9226.jpg', 'https://www.nebelspiegel.com/images/9226_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Midnight Blue S190 Wool Beaver Look', 'midnight-blue-s190-wool-beaver-look-9227', 'Midnight Blue S190 Wool Beaver Look from Zegna. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9227.jpg', 'https://www.nebelspiegel.com/images/9227_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Navy Blue Wool-silk Panama', 'navy-blue-wool-silk-panama-9228', 'Navy Blue Wool-silk Panama from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9228.jpg', 'https://www.nebelspiegel.com/images/9228_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Dark Blue-midnight Blue Wool-silk Glencheck', 'dark-blue-midnight-blue-wool-silk-glencheck-9229', 'Dark Blue-midnight Blue Wool-silk Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9229.jpg', 'https://www.nebelspiegel.com/images/9229_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Storm Blue Wool-silk Panama', 'storm-blue-wool-silk-panama-9230', 'Storm Blue Wool-silk Panama from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9230.jpg', 'https://www.nebelspiegel.com/images/9230_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Light Teal-charcoal Wool-silk Glencheck', 'light-teal-charcoal-wool-silk-glencheck-9231', 'Light Teal-charcoal Wool-silk Glencheck from Loro Piana. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9231.jpg', 'https://www.nebelspiegel.com/images/9231_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Mint Green-l.grey Alpaca-wool-cotton Blend Herringbone', 'mint-green-l-grey-alpaca-wool-cotton-blend-herringbone-9232', 'Mint Green-l.grey Alpaca-wool-cotton Blend Herringbone from Ferla. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9232.jpg', 'https://www.nebelspiegel.com/images/9232_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Dark Sage Wool-silk Panama', 'dark-sage-wool-silk-panama-9233', 'Dark Sage Wool-silk Panama from Carlo Barbera. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9233.jpg', 'https://www.nebelspiegel.com/images/9233_1.jpg'),
  ((select id from public.retailers where slug = 'atelier-demo'), 'Light Forest Green S190 Wool Beaver Look', 'light-forest-green-s190-wool-beaver-look-9234', 'Light Forest Green S190 Wool Beaver Look from Zegna. Cut and finished for Atelier Demo.', 'active', false, 'https://www.nebelspiegel.com/images/9234.jpg', 'https://www.nebelspiegel.com/images/9234_1.jpg')
on conflict (retailer_id, slug) do nothing;

insert into public.product_variants (product_id, sku, size, price_amount_minor_units, price_currency, inventory_quantity)
values
  ((select id from public.products where slug = 'greige-cotton-corduroy-6090' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6090', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'bone-wool-blend-twill-6091' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6091', '50', 154000, 'USD', 24),
  ((select id from public.products where slug = 'ivory-taupe-wool-glencheck-6092' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6092', '50', 179000, 'USD', 24),
  ((select id from public.products where slug = 'cedar-brown-silk-wool-cashmere-glencheck-6093' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6093', '50', 224000, 'USD', 24),
  ((select id from public.products where slug = 'chocolate-brown-wool-twill-6095' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6095', '50', 184000, 'USD', 24),
  ((select id from public.products where slug = 'dark-brown-wool-silk-linen-glencheck-6096' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6096', '50', 199000, 'USD', 24),
  ((select id from public.products where slug = 'mauve-cotton-corduroy-6097' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6097', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'pale-pink-alpaca-wool-blend-white-pin-stripes-6098' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6098', '50', 224000, 'USD', 24),
  ((select id from public.products where slug = 'dusty-pink-dark-brown-silk-wool-cashmere-glencheck-6099' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6099', '50', 224000, 'USD', 24),
  ((select id from public.products where slug = 'light-blue-wool-blend-twill-6100' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6100', '50', 154000, 'USD', 24),
  ((select id from public.products where slug = 'dark-blue-midnight-blue-wool-glencheck-6101' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6101', '50', 179000, 'USD', 24),
  ((select id from public.products where slug = 'indigo-blue-wool-twill-6102' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6102', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'midnight-blue-wool-twill-6103' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6103', '50', 199000, 'USD', 24),
  ((select id from public.products where slug = 'prussian-blue-cotton-corduroy-6104' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6104', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'petrol-midnight-blue-wool-micro-effect-6105' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6105', '50', 174000, 'USD', 24),
  ((select id from public.products where slug = 'storm-blue-silk-wool-cashmere-glencheck-6106' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6106', '50', 224000, 'USD', 24),
  ((select id from public.products where slug = 'teal-cotton-corduroy-6107' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6107', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'petrol-wool-blend-twill-6108' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6108', '50', 154000, 'USD', 24),
  ((select id from public.products where slug = 'black-white-wool-glencheck-6109' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '6109', '50', 179000, 'USD', 24),
  ((select id from public.products where slug = 'ivory-wool-silk-herringbone-9209' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9209', '50', 124000, 'USD', 24),
  ((select id from public.products where slug = 'sand-wool-silk-panama-9210' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9210', '50', 109000, 'USD', 24),
  ((select id from public.products where slug = 'bone-s190-wool-beaver-look-9211' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9211', '50', 204000, 'USD', 24),
  ((select id from public.products where slug = 'ivory-l-brown-wool-silk-glencheck-9212' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9212', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'beige-wool-silk-basketweave-9213' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9213', '50', 124000, 'USD', 24),
  ((select id from public.products where slug = 'ivory-taupe-wool-silk-cashmere-glencheck-9215' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9215', '50', 144000, 'USD', 24),
  ((select id from public.products where slug = 'mocha-s190-wool-beaver-look-9216' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9216', '50', 204000, 'USD', 24),
  ((select id from public.products where slug = 'coffee-brown-wool-silk-panama-9217' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9217', '50', 109000, 'USD', 24),
  ((select id from public.products where slug = 'dark-brown-midnight-blue-wool-silk-glencheck-9218' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9218', '50', 124000, 'USD', 24),
  ((select id from public.products where slug = 'cognac-wool-silk-panama-9219' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9219', '50', 109000, 'USD', 24),
  ((select id from public.products where slug = 'light-amber-wool-silk-linen-sharkskin-9220' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9220', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'copper-l-amber-wool-silk-glencheck-9221' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9221', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'maroon-ivory-wool-alpaca-blend-houndstooth-9222' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9222', '50', 154000, 'USD', 24),
  ((select id from public.products where slug = 'wine-red-wool-silk-panama-9223' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9223', '50', 109000, 'USD', 24),
  ((select id from public.products where slug = 'dusty-pink-maroon-wool-silk-glencheck-9224' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9224', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'purple-wool-silk-linen-sharkskin-9225' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9225', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'neapolitan-blue-wool-silk-cashmere-glencheck-9226' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9226', '50', 144000, 'USD', 24),
  ((select id from public.products where slug = 'midnight-blue-s190-wool-beaver-look-9227' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9227', '50', 204000, 'USD', 24),
  ((select id from public.products where slug = 'navy-blue-wool-silk-panama-9228' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9228', '50', 109000, 'USD', 24),
  ((select id from public.products where slug = 'dark-blue-midnight-blue-wool-silk-glencheck-9229' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9229', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'storm-blue-wool-silk-panama-9230' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9230', '50', 109000, 'USD', 24),
  ((select id from public.products where slug = 'light-teal-charcoal-wool-silk-glencheck-9231' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9231', '50', 139000, 'USD', 24),
  ((select id from public.products where slug = 'mint-green-l-grey-alpaca-wool-cotton-blend-herringbone-9232' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9232', '50', 159000, 'USD', 24),
  ((select id from public.products where slug = 'dark-sage-wool-silk-panama-9233' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9233', '50', 109000, 'USD', 24),
  ((select id from public.products where slug = 'light-forest-green-s190-wool-beaver-look-9234' and retailer_id = (select id from public.retailers where slug = 'atelier-demo')), '9234', '50', 204000, 'USD', 24)
on conflict (product_id, sku) do nothing;
