-- Supabase's default privileges grant EXECUTE on every new function in
-- public straight to anon and authenticated (and ALL on new tables). The
-- migrations below revoked only from PUBLIC, which does not remove those
-- direct grants, so functions meant for signed-in customers were callable
-- logged out, and server-only jobs (claim_pending_emails, the Stripe event
-- recorder, the visualisation and scan job completers, login-email
-- recognition) were callable by any signed-in user.
--
-- Each function here was revoked from PUBLIC by its own migration and never
-- granted to the role named. Functions that RLS policies, views or defaults
-- call are left alone: a policy evaluates as the caller.
--
-- And the tables whose writes go only through an RPC lose direct INSERT.

-- Not for logged-out callers ----------------------------------------
revoke execute on function public._service_assert_staff_retailer(uuid) from anon;
revoke execute on function public._service_history_insert(uuid,uuid,uuid,uuid,text,text,uuid) from anon;
revoke execute on function public.accept_platform_staff_invite(uuid) from anon;
revoke execute on function public.accept_retailer_staff_invite(uuid) from anon;
revoke execute on function public.add_alteration_task(uuid,text,text,work_classification,uuid,text,uuid) from anon;
revoke execute on function public.add_alteration_task_note(uuid,text) from anon;
revoke execute on function public.add_concept_scan_selection(uuid,text) from anon;
revoke execute on function public.add_fitting_observation(uuid,text,text,work_classification) from anon;
revoke execute on function public.add_to_cart(uuid,uuid,integer) from anon;
revoke execute on function public.add_wedding_inspiration_item(uuid,text,text) from anon;
revoke execute on function public.add_wedding_party_member(uuid,text,text,wedding_party_member_role) from anon;
revoke execute on function public.anonymize_behavioral_events_for_customer(uuid,uuid) from anon;
revoke execute on function public.anonymize_expired_behavioral_events(integer) from anon;
revoke execute on function public.approve_conversation_ai_draft(uuid,text) from anon;
revoke execute on function public.approve_fit_profile_candidate(uuid,text) from anon;
revoke execute on function public.approve_payroll_period(uuid) from anon;
revoke execute on function public.assign_alteration_work_order(uuid,uuid,date) from anon;
revoke execute on function public.assign_service_advisor(uuid,uuid) from anon;
revoke execute on function public.begin_silhouette_capture(uuid) from anon;
revoke execute on function public.book_appointment_from_consultation(uuid,appointment_type,timestamp with time zone,timestamp with time zone,text,uuid) from anon;
revoke execute on function public.cancel_my_appointment(uuid,text) from anon;
revoke execute on function public.cancel_wardrobe_visualization_job(uuid) from anon;
revoke execute on function public.capture_behavioral_event(uuid,text,jsonb,text,uuid,timestamp with time zone,text,text,jsonb,text,timestamp with time zone,uuid,uuid,text,text,timestamp with time zone,text,text) from anon;
revoke execute on function public.check_academy_roleplay_grade_session_tenant() from anon;
revoke execute on function public.check_corporate_announcement_programme_tenant() from anon;
revoke execute on function public.check_corporate_manager_account_tenant() from anon;
revoke execute on function public.check_corporate_wearer_customer_tenant() from anon;
revoke execute on function public.checkout_cart(uuid,jsonb) from anon;
revoke execute on function public.claim_conversation(uuid) from anon;
revoke execute on function public.claim_pending_emails(integer) from anon;
revoke execute on function public.claim_pending_message_attachment_scan_jobs(integer) from anon;
revoke execute on function public.claim_pending_sms(integer) from anon;
revoke execute on function public.claim_pending_wardrobe_visualization_jobs(integer) from anon;
revoke execute on function public.clock_in() from anon;
revoke execute on function public.clock_out() from anon;
revoke execute on function public.complete_campaign_challenge(uuid) from anon;
revoke execute on function public.complete_message_attachment_scan_job(uuid,text,text) from anon;
revoke execute on function public.complete_wardrobe_visualization_job(uuid,text,text,text,text,integer) from anon;
revoke execute on function public.complete_wedding_aftercare_plan(uuid) from anon;
revoke execute on function public.confirm_fit_profile_candidate(uuid) from anon;
revoke execute on function public.confirm_silhouette_analysis_candidate(uuid) from anon;
revoke execute on function public.correct_own_customer_fact(uuid,text,text,text) from anon;
revoke execute on function public.correct_payroll_entry(uuid,uuid,timestamp with time zone,timestamp with time zone,text) from anon;
revoke execute on function public.create_alteration_intake(uuid,uuid,garment_source_kind,text,text,text,text,text,jsonb,text,text,uuid,text,date,jsonb,jsonb) from anon;
revoke execute on function public.create_conversation_proposal(uuid,text,text,jsonb,jsonb,integer,text,boolean,timestamp with time zone) from anon;
revoke execute on function public.create_my_referral(uuid,text) from anon;
revoke execute on function public.decide_alteration_price_change(uuid,price_change_proposal_status,text) from anon;
revoke execute on function public.decide_service_weekly_plan(uuid,text,text) from anon;
revoke execute on function public.decide_silhouette_analysis_candidate(uuid,text,text) from anon;
revoke execute on function public.derive_alteration_attachment_actor() from anon;
revoke execute on function public.derive_alteration_custody_actor() from anon;
revoke execute on function public.derive_alteration_fulfillment_actor() from anon;
revoke execute on function public.dismiss_conversation_ai_draft(uuid) from anon;
revoke execute on function public.dispatch_alteration_grid_snapshot(uuid,uuid[],text) from anon;
revoke execute on function public.end_academy_roleplay_session(uuid,text) from anon;
revoke execute on function public.enforce_entity_metadata_assignment_tenancy() from anon;
revoke execute on function public.enforce_knowledge_object_concept_tenancy() from anon;
revoke execute on function public.enforce_knowledge_object_relation_tenancy() from anon;
revoke execute on function public.enforce_metadata_concept_edge_tenancy() from anon;
revoke execute on function public.enforce_outfit_slot_tenancy() from anon;
revoke execute on function public.enforce_outfit_tenancy() from anon;
revoke execute on function public.enforce_product_fabric_composition_tenancy() from anon;
revoke execute on function public.enforce_product_fabric_composition_total() from anon;
revoke execute on function public.enforce_product_fabric_profile_tenancy() from anon;
revoke execute on function public.enforce_retailer_concept_override_tenancy() from anon;
revoke execute on function public.enforce_retailer_knowledge_override_tenancy() from anon;
revoke execute on function public.enforce_roadmap_gap_tenancy() from anon;
revoke execute on function public.enforce_roadmap_goal_tenancy() from anon;
revoke execute on function public.enforce_roadmap_stage_tenancy() from anon;
revoke execute on function public.enforce_style_portrait_reference_tenancy() from anon;
revoke execute on function public.enforce_wardrobe_attachment_scope() from anon;
revoke execute on function public.enforce_wardrobe_item_reference_tenancy() from anon;
revoke execute on function public.enforce_wardrobe_roadmap_gap_disposition_tenancy() from anon;
revoke execute on function public.enforce_wardrobe_roadmap_tenancy() from anon;
revoke execute on function public.enforce_wardrobe_visualization_feedback_tenancy() from anon;
revoke execute on function public.enforce_wardrobe_visualization_job_tenancy() from anon;
revoke execute on function public.enqueue_campaign_delivery_notification(uuid,uuid,text,text,text,text) from anon;
revoke execute on function public.enqueue_gift_invitation_email(uuid,text) from anon;
revoke execute on function public.enqueue_morning_routine_delivery_notification(uuid,uuid,text,text,text,text) from anon;
revoke execute on function public.enqueue_style_portrait_preview_job(uuid,uuid,uuid,uuid,text,text,jsonb,text) from anon;
revoke execute on function public.enqueue_wardrobe_visualization_job(uuid,uuid,uuid,uuid,uuid,text,text,jsonb,text) from anon;
revoke execute on function public.enroll_campaign_challenge(uuid,uuid,uuid) from anon;
revoke execute on function public.enroll_service_membership(uuid,uuid,uuid,text,boolean) from anon;
revoke execute on function public.ensure_customer_style_profile(uuid) from anon;
revoke execute on function public.ensure_default_retailer_virtual_try_on_policy() from anon;
revoke execute on function public.ensure_default_retailer_visual_preset() from anon;
revoke execute on function public.ensure_interaction_session(uuid,uuid,timestamp with time zone,text,text,text,integer) from anon;
revoke execute on function public.ensure_loyalty_milestone_definitions(uuid) from anon;
revoke execute on function public.ensure_my_loyalty_account(uuid) from anon;
revoke execute on function public.expire_due_prospect_demo_environments() from anon;
revoke execute on function public.generate_prospect_demo_environment(uuid,text,text,timestamp with time zone,jsonb,uuid,text) from anon;
revoke execute on function public.generate_prospect_demo_preview(uuid,text,text,jsonb) from anon;
revoke execute on function public.get_my_service_care_status() from anon;
revoke execute on function public.get_or_create_my_conversation(uuid) from anon;
revoke execute on function public.get_or_create_staff_conversation(uuid) from anon;
revoke execute on function public.get_platform_analytics(timestamp with time zone) from anon;
revoke execute on function public.get_retailer_analytics(uuid,timestamp with time zone) from anon;
revoke execute on function public.grant_service_entitlement(uuid,text,integer,text,text) from anon;
revoke execute on function public.link_my_corporate_manager_account() from anon;
revoke execute on function public.link_my_customer_accounts() from anon;
revoke execute on function public.link_my_wearer_account() from anon;
revoke execute on function public.link_service_booking_appointment(uuid,uuid) from anon;
revoke execute on function public.loyalty_milestone_slug_matches(text,text[]) from anon;
revoke execute on function public.mark_alteration_customer_notified(uuid) from anon;
revoke execute on function public.mark_conversation_read(uuid) from anon;
revoke execute on function public.mark_gift_invitation_refunded(uuid,integer,text) from anon;
revoke execute on function public.mark_morning_routine_review(uuid,text) from anon;
revoke execute on function public.notify_customer_of_appointment_change(uuid,text,text) from anon;
revoke execute on function public.notify_customer_paid_care_booking_confirmed() from anon;
revoke execute on function public.open_payroll_period(uuid,date,date) from anon;
revoke execute on function public.payroll_current_staff(uuid) from anon;
revoke execute on function public.payroll_export_checksum(text) from anon;
revoke execute on function public.persist_morning_routine_selection(uuid,uuid,date,text,jsonb,jsonb) from anon;
revoke execute on function public.persist_style_profile_recompute(uuid,jsonb,jsonb,timestamp with time zone) from anon;
revoke execute on function public.place_corporate_order(uuid,uuid,jsonb,order_channel,text) from anon;
revoke execute on function public.place_order(uuid,uuid,integer) from anon;
revoke execute on function public.propose_alteration_price_change(uuid,uuid,integer,text,uuid) from anon;
revoke execute on function public.propose_fit_profile_candidate(uuid[],jsonb,text) from anon;
revoke execute on function public.propose_service_weekly_plan(uuid,date,jsonb,text) from anon;
revoke execute on function public.propose_wedding_date_candidate(uuid,date) from anon;
revoke execute on function public.protect_sartorial_rule_identity() from anon;
revoke execute on function public.protect_wardrobe_item_identity() from anon;
revoke execute on function public.protect_wardrobe_roadmap_gap_disposition_identity() from anon;
revoke execute on function public.protect_wardrobe_roadmap_identity() from anon;
revoke execute on function public.publish_catalogue_import_row(uuid) from anon;
revoke execute on function public.recognize_customer_login_email(text,text,text,text) from anon;
revoke execute on function public.record_advisor_rectangle_facts(uuid,uuid,uuid,timestamp with time zone,jsonb,text) from anon;
revoke execute on function public.record_alteration_task_cost_allocation(uuid,integer,integer,integer,text,text) from anon;
revoke execute on function public.record_campaign_delivery_audit(uuid,uuid,uuid,date,text,timestamp with time zone,text,text,text,uuid) from anon;
revoke execute on function public.record_consultation_attachment(uuid,text,text,text,text,bigint,text,text,uuid,uuid) from anon;
revoke execute on function public.record_customer_access_event(text,text,uuid,text,text) from anon;
revoke execute on function public.record_customer_ai_generation(uuid,ai_generation_status,text,text,jsonb,text,integer) from anon;
revoke execute on function public.record_customer_tableservice_grounded(uuid,ai_generation_status,text,text,text,jsonb,text,integer) from anon;
revoke execute on function public.record_message_attachment(uuid,text,text,text,bigint) from anon;
revoke execute on function public.record_morning_routine_delivery_audit(uuid,uuid,date,text,timestamp with time zone,uuid,text,uuid) from anon;
revoke execute on function public.record_payroll_export(uuid) from anon;
revoke execute on function public.record_popup_impression(uuid,uuid,text,uuid) from anon;
revoke execute on function public.record_service_care(uuid,text,text,uuid,uuid,uuid,uuid) from anon;
revoke execute on function public.record_service_cost(uuid,text,integer,text,uuid,text) from anon;
revoke execute on function public.record_service_fulfilment(uuid,text,text,timestamp with time zone,text) from anon;
revoke execute on function public.record_silhouette_capture(uuid,text,text,text,bigint) from anon;
revoke execute on function public.record_stripe_payment_event(text,text,uuid,text,integer,text,payment_status,integer) from anon;
revoke execute on function public.record_style_preference_evidence(uuid,uuid,text,text,numeric,uuid) from anon;
revoke execute on function public.record_wardrobe_attachment(uuid,text,text,text,bigint,text,uuid) from anon;
revoke execute on function public.record_wardrobe_lifecycle_event(uuid,text,text,text,timestamp with time zone) from anon;
revoke execute on function public.redeem_my_reward(uuid) from anon;
revoke execute on function public.redeem_wedding_guest_voucher(uuid) from anon;
revoke execute on function public.reject_fit_profile_candidate(uuid,text) from anon;
revoke execute on function public.release_message_attachment(uuid) from anon;
revoke execute on function public.remove_inferred_style_preference(uuid,uuid,text) from anon;
revoke execute on function public.request_appointment(uuid,appointment_type,timestamp with time zone,timestamp with time zone,text,uuid) from anon;
revoke execute on function public.request_appointment_as_wearer(uuid,appointment_type,timestamp with time zone,timestamp with time zone,text) from anon;
revoke execute on function public.request_one_click_checkout_eligibility(uuid) from anon;
revoke execute on function public.request_service_booking(uuid,text,text,timestamp with time zone,text) from anon;
revoke execute on function public.reschedule_my_appointment(uuid,timestamp with time zone,timestamp with time zone) from anon;
revoke execute on function public.reserve_virtual_try_on_generation(uuid,uuid,uuid,uuid,text,text,text,text,text,text,text[],boolean,integer,text,boolean,boolean) from anon;
revoke execute on function public.resolve_payroll_exception(uuid) from anon;
revoke execute on function public.respond_to_conversation_proposal(uuid,text) from anon;
revoke execute on function public.restore_retailer_brand_theme(uuid,integer) from anon;
revoke execute on function public.retailer_has_entitlement(uuid,text) from anon;
revoke execute on function public.retry_message_attachment_scan(uuid) from anon;
revoke execute on function public.review_catalogue_import_task(uuid,metadata_review_task_status) from anon;
revoke execute on function public.review_metadata_assignment(uuid,metadata_review_status) from anon;
revoke execute on function public.revoke_gift_invitation(uuid,text) from anon;
revoke execute on function public.rsvp_to_event(uuid,event_rsvp_status) from anon;
revoke execute on function public.save_alteration_grid_snapshot(uuid,jsonb,text) from anon;
revoke execute on function public.save_prospect_demo_configuration(uuid,uuid,jsonb,text,text,jsonb,text[],text[],text,text[]) from anon;
revoke execute on function public.save_retailer_brand_theme(uuid,jsonb,text) from anon;
revoke execute on function public.save_suit_configuration_intent(uuid,text,text,text,smallint) from anon;
revoke execute on function public.save_wishlist_item(uuid,uuid) from anon;
revoke execute on function public.seed_default_paid_care_service_prices(uuid) from anon;
revoke execute on function public.seed_paid_care_prices_for_new_retailer() from anon;
revoke execute on function public.send_conversation_message(uuid,text) from anon;
revoke execute on function public.set_alteration_operation_price(uuid,integer,uuid) from anon;
revoke execute on function public.set_conversation_status(uuid,text) from anon;
revoke execute on function public.set_customer_consent(uuid,text,text,text) from anon;
revoke execute on function public.set_product_fabric_profile(uuid,uuid,numeric,text,jsonb) from anon;
revoke execute on function public.set_prospect_demo_publication(uuid,boolean) from anon;
revoke execute on function public.set_service_membership_status(uuid,text) from anon;
revoke execute on function public.set_wedding_design_choice(uuid,text,text,uuid,boolean) from anon;
revoke execute on function public.settle_virtual_try_on_generation(uuid,text,text,integer,integer,text,integer,text,text,integer,text,text) from anon;
revoke execute on function public.start_academy_roleplay_session(uuid,text) from anon;
revoke execute on function public.start_silhouette_analysis_session(uuid) from anon;
revoke execute on function public.submit_academy_roleplay_turn(uuid,text,text) from anon;
revoke execute on function public.submit_concept_selection(uuid) from anon;
revoke execute on function public.submit_wardrobe_self_scan(uuid,text,boolean,text,boolean,timestamp with time zone,timestamp with time zone,text) from anon;
revoke execute on function public.suppress_customer_email_on_terminal_failure() from anon;
revoke execute on function public.suppress_customer_sms_on_terminal_failure() from anon;
revoke execute on function public.sync_corporate_manager_claim() from anon;
revoke execute on function public.sync_corporate_wearer_claim() from anon;
revoke execute on function public.sync_loyalty_milestones_for_order(uuid) from anon;
revoke execute on function public.toggle_wedding_date_vote(uuid) from anon;
revoke execute on function public.toggle_wishlist_item(uuid,uuid) from anon;
revoke execute on function public.transition_alteration_work_order(uuid,alteration_work_order_status,text,boolean) from anon;
revoke execute on function public.transition_service_booking(uuid,text,text,boolean) from anon;
revoke execute on function public.update_alteration_task_status(uuid,alteration_task_status,text) from anon;
revoke execute on function public.update_cart_line(uuid,integer) from anon;
revoke execute on function public.update_commercial_plan(uuid,text,text,text,integer,text,boolean,integer,text,integer,text[],boolean) from anon;
revoke execute on function public.update_my_default_shipping_address(uuid,jsonb) from anon;
revoke execute on function public.update_my_profile_details(uuid,text,date,text) from anon;
revoke execute on function public.update_product_catalogue(uuid,text,text,text,product_status,boolean,boolean,text,uuid[]) from anon;
revoke execute on function public.update_wedding_party_member_status(uuid,wedding_party_member_fitting_status) from anon;
revoke execute on function public.update_workshop_assignment(uuid,uuid,date) from anon;
revoke execute on function public.upsert_campaign_challenge_look(uuid,integer,text,jsonb) from anon;
revoke execute on function public.upsert_declared_style_preference(uuid,uuid,text,text) from anon;
revoke execute on function public.upsert_morning_routine_subscription(uuid,uuid,boolean,text,text,integer,text[],integer,integer) from anon;
revoke execute on function public.upsert_my_labeled_address(uuid,text,jsonb) from anon;
revoke execute on function public.validate_conversation_message_capture_session() from anon;
revoke execute on function public.wardrobe_item_self_scan_eligible(wardrobe_items) from anon;
revoke execute on function public.withdraw_silhouette_analysis_consent(uuid) from anon;

-- Server-only (service_role) or trigger functions ------------------------
revoke execute on function public._service_assert_staff_retailer(uuid) from authenticated;
revoke execute on function public._service_history_insert(uuid,uuid,uuid,uuid,text,text,uuid) from authenticated;
revoke execute on function public.anonymize_behavioral_events_for_customer(uuid,uuid) from authenticated;
revoke execute on function public.anonymize_expired_behavioral_events(integer) from authenticated;
revoke execute on function public.check_academy_roleplay_grade_session_tenant() from authenticated;
revoke execute on function public.check_corporate_announcement_programme_tenant() from authenticated;
revoke execute on function public.check_corporate_manager_account_tenant() from authenticated;
revoke execute on function public.check_corporate_wearer_customer_tenant() from authenticated;
revoke execute on function public.claim_pending_emails(integer) from authenticated;
revoke execute on function public.claim_pending_message_attachment_scan_jobs(integer) from authenticated;
revoke execute on function public.claim_pending_sms(integer) from authenticated;
revoke execute on function public.claim_pending_wardrobe_visualization_jobs(integer) from authenticated;
revoke execute on function public.complete_message_attachment_scan_job(uuid,text,text) from authenticated;
revoke execute on function public.complete_wardrobe_visualization_job(uuid,text,text,text,text,integer) from authenticated;
revoke execute on function public.derive_alteration_attachment_actor() from authenticated;
revoke execute on function public.derive_alteration_custody_actor() from authenticated;
revoke execute on function public.derive_alteration_fulfillment_actor() from authenticated;
revoke execute on function public.enforce_entity_metadata_assignment_tenancy() from authenticated;
revoke execute on function public.enforce_knowledge_object_concept_tenancy() from authenticated;
revoke execute on function public.enforce_knowledge_object_relation_tenancy() from authenticated;
revoke execute on function public.enforce_metadata_concept_edge_tenancy() from authenticated;
revoke execute on function public.enforce_outfit_slot_tenancy() from authenticated;
revoke execute on function public.enforce_outfit_tenancy() from authenticated;
revoke execute on function public.enforce_product_fabric_composition_tenancy() from authenticated;
revoke execute on function public.enforce_product_fabric_composition_total() from authenticated;
revoke execute on function public.enforce_product_fabric_profile_tenancy() from authenticated;
revoke execute on function public.enforce_retailer_concept_override_tenancy() from authenticated;
revoke execute on function public.enforce_retailer_knowledge_override_tenancy() from authenticated;
revoke execute on function public.enforce_roadmap_gap_tenancy() from authenticated;
revoke execute on function public.enforce_roadmap_goal_tenancy() from authenticated;
revoke execute on function public.enforce_roadmap_stage_tenancy() from authenticated;
revoke execute on function public.enforce_style_portrait_reference_tenancy() from authenticated;
revoke execute on function public.enforce_wardrobe_attachment_scope() from authenticated;
revoke execute on function public.enforce_wardrobe_item_reference_tenancy() from authenticated;
revoke execute on function public.enforce_wardrobe_roadmap_gap_disposition_tenancy() from authenticated;
revoke execute on function public.enforce_wardrobe_roadmap_tenancy() from authenticated;
revoke execute on function public.enforce_wardrobe_visualization_feedback_tenancy() from authenticated;
revoke execute on function public.enforce_wardrobe_visualization_job_tenancy() from authenticated;
revoke execute on function public.enqueue_campaign_delivery_notification(uuid,uuid,text,text,text,text) from authenticated;
revoke execute on function public.enqueue_morning_routine_delivery_notification(uuid,uuid,text,text,text,text) from authenticated;
revoke execute on function public.ensure_default_retailer_virtual_try_on_policy() from authenticated;
revoke execute on function public.ensure_default_retailer_visual_preset() from authenticated;
revoke execute on function public.loyalty_milestone_slug_matches(text,text[]) from authenticated;
revoke execute on function public.notify_customer_paid_care_booking_confirmed() from authenticated;
revoke execute on function public.payroll_current_staff(uuid) from authenticated;
revoke execute on function public.payroll_export_checksum(text) from authenticated;
revoke execute on function public.protect_sartorial_rule_identity() from authenticated;
revoke execute on function public.protect_wardrobe_item_identity() from authenticated;
revoke execute on function public.protect_wardrobe_roadmap_gap_disposition_identity() from authenticated;
revoke execute on function public.protect_wardrobe_roadmap_identity() from authenticated;
revoke execute on function public.recognize_customer_login_email(text,text,text,text) from authenticated;
revoke execute on function public.record_campaign_delivery_audit(uuid,uuid,uuid,date,text,timestamp with time zone,text,text,text,uuid) from authenticated;
revoke execute on function public.record_morning_routine_delivery_audit(uuid,uuid,date,text,timestamp with time zone,uuid,text,uuid) from authenticated;
revoke execute on function public.record_stripe_payment_event(text,text,uuid,text,integer,text,payment_status,integer) from authenticated;
revoke execute on function public.seed_default_paid_care_service_prices(uuid) from authenticated;
revoke execute on function public.seed_paid_care_prices_for_new_retailer() from authenticated;
revoke execute on function public.settle_virtual_try_on_generation(uuid,text,text,integer,integer,text,integer,text,text,integer,text,text) from authenticated;
revoke execute on function public.suppress_customer_email_on_terminal_failure() from authenticated;
revoke execute on function public.suppress_customer_sms_on_terminal_failure() from authenticated;
revoke execute on function public.sync_corporate_manager_claim() from authenticated;
revoke execute on function public.sync_corporate_wearer_claim() from authenticated;
revoke execute on function public.validate_conversation_message_capture_session() from authenticated;
revoke execute on function public.wardrobe_item_self_scan_eligible(wardrobe_items) from authenticated;

-- RPC-only writes --------------------------------------------------------
revoke insert, update, delete on table public.store_feedback_signals from anon, authenticated;
revoke insert, update, delete on table public.product_fabric_profiles from anon, authenticated;
revoke insert, update, delete on table public.product_fabric_composition from anon, authenticated;
revoke insert, update, delete on table public.metadata_assignment_reviews from anon, authenticated;
revoke insert, update, delete on table public.gift_invitation_state_history from anon, authenticated;
revoke insert, update, delete on table public.message_attachments from anon;
