-- Care and collar knowledge cards. Both topics had only 1 placeholder
-- knowledge object each ('Knowledge fixture care'/'collar') -- real
-- garment-care guidance (dry cleaning, pressing, storage, per fibre)
-- and collar-style education (point/spread/cutaway/button-down/club/
-- band) were entirely missing.

INSERT INTO public.knowledge_objects (id, retailer_id, topic, title, slug, summary, body, image_url, display_types, commercial_intent, priority, active, created_at, updated_at, deleted_at)
VALUES
  ('dc000000-0000-4000-8000-000000000001'::uuid, NULL, 'care'::public.knowledge_topic, E'Wool Suits: Dry Clean or Hand Wash?'::text, 'wool-suits-dry-clean-or-hand-wash'::text, E'Expert guidance on preserving wool suits via dry cleaning or gentle hand washing.'::text, E'Wool suits demand specialized care to maintain their shape, texture, and longevity. Dry cleaning is ideal for deep cleaning and removing odors without risking shrinkage, but excessive cycles can weaken fibers over time. Reserve it for seasonal storage or after heavy wear.

Hand washing, while riskier, can be done with lukewarm water and wool-specific detergents for light soil. Always lay flat to dry to prevent stretching. Spot cleaning between wears extends freshness. Regardless of method, avoid heat and harsh chemicals to preserve wool''s natural resilience.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000002'::uuid, NULL, 'care'::public.knowledge_topic, E'Steam and Press Like a Pro'::text, 'steam-and-press-like-a-pro'::text, E'Learn to refresh suits without unwanted shine, preserving their premium look.'::text, E'Steaming and pressing are essential for maintaining a sharp appearance, but improper techniques can leave fabrics with an unwanted sheen. Always use a steamer or iron on the lowest effective heat setting, and employ a pressing cloth to protect delicate materials. For wool suits, steam from the inside to relax fibers without flattening them, which can cause shine.

Avoid excessive pressure when pressing, especially on seams and edges, as this is where shine most often appears. For stubborn wrinkles, lightly mist the garment with water before steaming, but never apply direct heat to wet fabric. Regularly rotating your suits and allowing them to rest between wears reduces the need for frequent pressing, further preventing shine over time.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000003'::uuid, NULL, 'care'::public.knowledge_topic, E'Suit Storage Essentials'::text, 'suit-storage-essentials'::text, E'Choose the right hangers to preserve your suits'' shape and longevity.'::text, E'The foundation of proper suit care starts with the right hanger. Wide, contoured wooden hangers mimic the natural shoulder line, maintaining the jacket''s structure and preventing wrinkles. Wire or flimsy plastic hangers can distort the shoulders over time, leading to irreversible damage and costly alterations.

For optimal storage, select hangers with a rounded shape and sufficient width to support the garment. Cedar hangers offer added benefits, naturally repelling moths and absorbing moisture. Always hang trousers from the cuffs or waist to avoid creasing, and leave ample space between garments to ensure proper air circulation.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000004'::uuid, NULL, 'care'::public.knowledge_topic, E'Rotate suits to prolong elegance'::text, 'rotate-suits-to-prolong-elegance'::text, E'Strategic rotation preserves fabric integrity, maintaining a sharp appearance longer.'::text, E'Rotating between multiple suits allows each garment 24-48 hours to recover from wear, enabling fibers to relax and moisture to evaporate. This simple practice prevents excessive strain on seams and fabric, particularly in high-stress areas like elbows and knees. Natural fabrics like wool especially benefit from this rest period, which helps maintain their shape and drape over time.

Regular rotation also distributes wear evenly across your wardrobe, avoiding the premature aging of favored pieces. For optimal results, pair rotation with proper storage – use wide, padded hangers to support shoulder structure and ensure adequate breathing space between garments. This approach is particularly valuable for premium suits where fabric quality and construction details warrant extended longevity.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000005'::uuid, NULL, 'care'::public.knowledge_topic, E'Silk & Wool Stain Rescue'::text, 'silk-wool-stain-rescue'::text, E'Gentle techniques to remove stains from delicate silk and wool without damaging the fibers.'::text, E'Silk and wool require special care when treating stains due to their delicate fibers. Avoid harsh chemicals or vigorous rubbing, which can distort the fabric. Instead, blot stains immediately with a clean, damp cloth and mild soap. For oil-based stains, sprinkle cornstarch or talc to absorb excess before gently brushing it off.

Always test any cleaning solution on an inconspicuous area first. For persistent stains, consult a professional dry cleaner experienced with delicate fabrics. Never use bleach or high heat, as these can irreversibly damage silk and wool fibers. Proper prompt treatment preserves the fabric''s integrity and appearance.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000006'::uuid, NULL, 'care'::public.knowledge_topic, E'Mastering Linen Care with Ease'::text, 'mastering-linen-care-with-ease'::text, E'Keep your linen crisp and fresh without the hassle of excessive ironing.'::text, E'Linen is a luxurious fabric known for its breathability and timeless elegance. To maintain its natural texture and avoid excessive creasing, it’s essential to embrace its slightly rumpled look. After washing, gently shake out your linen garments and hang them to dry while still damp. This helps smooth out wrinkles naturally.

Ironing linen requires a delicate touch. Use a medium-hot iron and press while the fabric is slightly damp for best results. Alternatively, steam your linen to remove stubborn creases without flattening its characteristic texture. Overly pressing linen can strip away its natural charm. Store linen items folded or on padded hangers to preserve their shape and longevity.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000007'::uuid, NULL, 'care'::public.knowledge_topic, E'Preventing Cashmere Pilling'::text, 'preventing-cashmere-pilling'::text, E'Maintain your cashmere''s luxurious feel by preventing pilling with these expert care tips.'::text, E'Cashmere pilling, those small bobbles that form on the fabric''s surface, is a natural occurrence due to the delicate fibers rubbing together. While it doesn''t indicate poor quality, it can affect the garment''s appearance. Gentle handling and proper storage are key to minimizing pilling.

To prevent pilling, hand wash your cashmere in cool water with a mild detergent and lay it flat to dry. Avoid wringing or twisting the fabric. Store cashmere folded rather than hung to reduce stress on the fibers. For minor pilling, use a cashmere comb or a fabric shaver carefully to restore the smooth texture without damaging the garment.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000008'::uuid, NULL, 'care'::public.knowledge_topic, E'Seasonal Wool Care'::text, 'seasonal-wool-care'::text, E'Essential tips to protect fine woolens during summer storage and prevent moth damage.'::text, E'Proper seasonal storage is critical for maintaining the integrity of wool garments. Natural fibers like cashmere and merino are prime targets for moths, whose larvae can cause irreversible damage. Always clean items thoroughly before storing—moths are attracted to body oils and food residues. Use acid-free tissue paper to pad sleeves and folds, avoiding permanent creases. 

For moth protection, avoid synthetic mothballs which leave toxic residues and alter fabric pH. Opt for natural deterrents like cedar blocks, lavender sachets, or specially designed wool storage bags with antimicrobial properties. Store in a cool, dry place with consistent temperature—attic and basement storage risks humidity fluctuations. For heirloom-quality pieces, consider professional climate-controlled garment storage with routine inspection services.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000009'::uuid, NULL, 'collar'::public.knowledge_topic, E'The Sharp Point Collar'::text, 'the-sharp-point-collar'::text, E'A modern staple, the point collar balances versatility and sophistication for both business and casual looks.'::text, E'The point collar is a timeless choice characterized by its narrow, straight collar points that sit close to the shirt. Its clean lines and moderate spread make it a versatile option, equally suited for office wear or dressed-down occasions. This collar pairs well with most tie knots and works effortlessly under suits or solo with jeans.

For a polished look, opt for a point collar in crisp cotton or blended fabrics. Its understated elegance complements both classic and contemporary styles, making it a wardrobe essential. While subtle, the angle of the points can subtly influence the shirt''s overall aesthetic, offering a refined touch without overpowering the outfit.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000010'::uuid, NULL, 'collar'::public.knowledge_topic, E'Spread Collar Elegance'::text, 'spread-collar-elegance'::text, E'The spread collar balances modern style with timeless sophistication, ideal for versatile styling.'::text, E'A spread collar features wider-set points, creating a broader frame for the face and allowing more visibility of the tie knot. This design is favored for its contemporary yet classic appeal, making it a versatile choice for both business and formal occasions. The angle of the spread can vary, with moderate spreads offering everyday adaptability and extreme spreads leaning toward bold fashion statements.

Pair a spread collar with a well-proportioned tie knot, such as a Windsor or half-Windsor, to maintain balance. It complements most face shapes but particularly suits round or square faces by adding visual length. For premium dress shirts, look for reinforced collar stays and high-quality fabrics that hold their shape throughout the day.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000011'::uuid, NULL, 'collar'::public.knowledge_topic, E'Mastering the Cutaway Collar'::text, 'mastering-the-cutaway-collar'::text, E'Elevate your style with the sophisticated and versatile cutaway collar.'::text, E'The cutaway collar is a timeless choice for modern gentlemen seeking a polished look. Its wide-set points create a sharp, open neckline, ideal for showcasing ties and enhancing your overall appearance. This collar pairs perfectly with both formal and casual styles, making it a versatile addition to any wardrobe.

When selecting a cutaway collar shirt, consider the fabric and fit to ensure it complements your frame. Premium cotton or blended fabrics offer durability and comfort, while tailored cuts provide a sleek silhouette. Experiment with different tie knots and styles to maximize the collar''s impact.

Whether for business meetings or social events, the cutaway collar exudes confidence and sophistication. Its adaptability makes it a must-have for any discerning gentleman.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000012'::uuid, NULL, 'collar'::public.knowledge_topic, E'The Button-Down Collar''s Timeless Appeal'::text, 'the-button-down-collar-s-timeless-appeal'::text, E'A sporty yet refined collar that adds versatility to any shirt.'::text, E'The button-down collar originated in 19th-century polo, where players needed their collars to stay put during matches. Brooks Brothers later popularized it as a signature detail, blending athletic functionality with Ivy League elegance.

Today, it bridges casual and formal wear effortlessly. The discreet buttons anchor the collar points, preventing flare while maintaining a clean silhouette. Perfect for both open-necked relaxation and tie-ready polish, it''s a wardrobe workhorse that elevates oxford cloth to dressier fabrics like twill or poplin.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000013'::uuid, NULL, 'collar'::public.knowledge_topic, E'Sporty Elegance of the Club Collar'::text, 'sporty-elegance-of-the-club-collar'::text, E'The club collar’s rounded edges offer a softer, vintage-inspired alternative to rigid formal styles.'::text, E'Originally popular in the early 20th century, the club collar features distinctive rounded edges instead of sharp points, lending a relaxed yet refined aesthetic. Favored by British boarding school students and later adopted by Ivy League styles, it strikes a balance between smart and approachable. The shorter collar points sit higher on the neckline, making it ideal for tie-less looks or slim knit ties.

Modern iterations often appear on casual shirts or as a subtle twist on formalwear. Its versatility shines when paired with unstructured blazers or textured tweeds. While traditionally cut from crisp cotton, luxury versions may use brushed oxford or linen-silk blends for added drape. The club collar works particularly well for men with narrower faces, as the curves soften angular jawlines.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('dc000000-0000-4000-8000-000000000014'::uuid, NULL, 'collar'::public.knowledge_topic, E'The Understated Mandarin Collar'::text, 'the-understated-mandarin-collar'::text, E'A band collar offers a sleek, modern twist on traditional dress shirts.'::text, E'The mandarin or band collar is a distinctive style characterized by its short, straight standing band that sits close to the neck without fold-over points. Originating from traditional East Asian attire, this collar design delivers a minimalist, contemporary aesthetic well-suited for both casual and formal ensembles. It pairs especially well with jackets and sweaters, providing a clean, uncluttered line.

While band collars eliminate the need for ties, they demand precise fit around the neck since there''s no adjustable opening. Premium iterations often feature reinforced inner structure to maintain shape. When selecting a mandarin collar shirt, consider fabrics with enough body to support the collar''s upright position. This style particularly complements slim-cut suits and textured knitwear for a refined yet fashion-forward statement.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL)
ON CONFLICT (slug) WHERE retailer_id IS NULL DO UPDATE SET
  summary = excluded.summary,
  body = excluded.body,
  updated_at = now(),
  deleted_at = null;
