insert into public.alteration_catalogue_categories (code, name, description, display_order)
values
  ('suit', 'Suits', 'Coordinated two- and three-piece suits.', 10),
  ('jacket', 'Jackets & blazers', 'Tailored jackets, blazers and dinner jackets.', 20),
  ('trousers', 'Trousers', 'Tailored trousers and chinos.', 30),
  ('waistcoat', 'Waistcoats', 'Single- and double-breasted waistcoats.', 40),
  ('shirt', 'Shirts', 'Dress, formal and casual woven shirts.', 50),
  ('overcoat', 'Overcoats', 'Structured overcoats and topcoats.', 60),
  ('coat', 'Coats & outerwear', 'Casual coats, field jackets and rainwear.', 70),
  ('formalwear', 'Formalwear', 'Dinner suits, morning dress and eveningwear.', 80),
  ('denim', 'Denim', 'Jeans and denim garments.', 90),
  ('knitwear', 'Knitwear', 'Fine-gauge knitwear and knitted jackets.', 100),
  ('leather', 'Leather & suede', 'Leather and suede garments requiring specialist handling.', 110),
  ('accessories', 'Accessories', 'Ties, pocket squares, belts and soft accessories.', 120),
  ('other', 'Other garments', 'Unlisted premium garments and custom work.', 999);

with operation(category_code, code, name, description, minutes, display_order) as (
  values
    ('suit','suit_full_rebalance','Full suit balance','Coordinate jacket and trouser balance across a suit.',180,10),
    ('suit','suit_posture_correction','Suit posture correction','Coordinate front/back balance for erect or stooped posture.',240,20),
    ('suit','suit_finish_basting','Finish basted fitting','Complete agreed work following a basted fitting.',180,30),
    ('jacket','jacket_sleeve_length_cuff','Shorten/lengthen sleeves from cuff','Adjust sleeve length at cuff, preserving finish.',90,10),
    ('jacket','jacket_sleeve_length_shoulder','Shorten sleeves from shoulder','Adjust sleeve length at sleevehead.',180,20),
    ('jacket','jacket_sleeve_pitch','Correct sleeve pitch','Reset sleeve pitch for clean drape.',180,30),
    ('jacket','jacket_sleeve_narrow','Narrow sleeves','Reduce sleeve width through forearm or upper arm.',120,40),
    ('jacket','jacket_take_in_side_seams','Take in side seams','Reduce jacket body through side seams.',120,50),
    ('jacket','jacket_let_out_side_seams','Let out side seams','Release available side-seam inlay.',120,60),
    ('jacket','jacket_suppress_waist','Suppress waist','Shape jacket waist while retaining balance.',120,70),
    ('jacket','jacket_center_back','Adjust centre back seam','Take in or release centre back.',90,80),
    ('jacket','jacket_shorten_length','Shorten jacket length','Shorten hem and rebalance vents/pockets where possible.',240,90),
    ('jacket','jacket_collar_lower','Lower collar','Remove collar roll or excess below collar.',120,100),
    ('jacket','jacket_collar_raise','Raise collar','Add height or correct collar position where inlay permits.',150,110),
    ('jacket','jacket_neck_point','Adjust neck point','Correct lapel/neck point alignment.',180,120),
    ('jacket','jacket_shoulders_narrow','Narrow shoulders','Reduce shoulder width and reset sleeveheads.',300,130),
    ('jacket','jacket_shoulder_pad','Adjust shoulder padding','Add, remove or reshape shoulder padding.',150,140),
    ('jacket','jacket_chest_darts','Adjust chest/darts','Refine chest volume and front suppression.',180,150),
    ('jacket','jacket_vent_repair','Repair vents','Repair or reinforce side/centre vents.',120,160),
    ('jacket','jacket_button_move','Move buttons','Reposition front or cuff buttons.',45,170),
    ('jacket','jacket_lining_repair','Repair lining','Local lining repair or reinforcement.',90,180),
    ('jacket','jacket_reline','Full reline','Replace complete jacket lining.',360,190),
    ('jacket','jacket_hand_finish','Hand finishing','Buttonholes, pick stitching or specialist hand finishing.',180,200),
    ('trousers','trouser_plain_hem','Plain hem','Shorten or lengthen with plain machine-finished hem.',45,10),
    ('trousers','trouser_turnups','Hem with turn-ups','Create or adjust cuffed trouser hem.',60,20),
    ('trousers','trouser_original_finish','Preserve original finish','Adjust length while preserving original construction.',75,30),
    ('trousers','trouser_waist_take_in','Take in waist','Reduce waistband and seat cleanly.',90,40),
    ('trousers','trouser_waist_let_out','Let out waist','Release available waistband/seat inlay.',90,50),
    ('trousers','trouser_seat_adjust','Adjust seat','Correct excess or shortage through seat seam.',90,60),
    ('trousers','trouser_taper_knee_hem','Taper knee to hem','Reduce lower-leg width.',75,70),
    ('trousers','trouser_taper_full_leg','Taper full leg','Reduce thigh, knee and hem width.',120,80),
    ('trousers','trouser_thigh_adjust','Adjust thigh','Take in or release thigh through seams.',90,90),
    ('trousers','trouser_rise_adjust','Adjust rise','Correct front/back rise where construction permits.',180,100),
    ('trousers','trouser_crotch_adjust','Adjust fork/crotch','Correct fork balance and crotch curve.',150,110),
    ('trousers','trouser_side_seams','Adjust side seams','Take in or release through side seams.',120,120),
    ('trousers','trouser_replace_zip','Replace zip','Replace trouser fly zip.',90,130),
    ('trousers','trouser_add_brace_buttons','Add brace buttons','Install internal brace buttons.',45,140),
    ('trousers','trouser_add_side_adjusters','Add/repair side adjusters','Install or repair waistband adjusters.',120,150),
    ('trousers','trouser_recut','Major trouser recut','Comprehensive reshape requiring waistband removal.',300,160),
    ('waistcoat','waistcoat_side_seams','Adjust side seams','Take in or release waistcoat body.',90,10),
    ('waistcoat','waistcoat_back_strap','Adjust back strap','Shorten, replace or reposition back strap.',60,20),
    ('waistcoat','waistcoat_length','Adjust waistcoat length','Shorten and rebalance front points where possible.',180,30),
    ('waistcoat','waistcoat_shoulder','Adjust shoulders','Shorten shoulders and correct armholes.',120,40),
    ('waistcoat','waistcoat_reline','Reline waistcoat','Replace back/lining panels.',240,50),
    ('shirt','shirt_sleeve_length','Adjust sleeve length','Shorten sleeves and reset cuffs/plackets.',90,10),
    ('shirt','shirt_body_take_in','Take in body','Reduce side seams or add darts.',75,20),
    ('shirt','shirt_body_let_out','Let out body','Release available side-seam allowance.',75,30),
    ('shirt','shirt_shorten','Shorten shirt length','Shorten curved or straight hem.',60,40),
    ('shirt','shirt_collar_reduce','Reduce collar','Reduce collar circumference where construction permits.',150,50),
    ('shirt','shirt_cuff_adjust','Adjust cuffs','Move buttons or resize cuffs.',45,60),
    ('shirt','shirt_replace_collar_cuffs','Replace collar/cuffs','Specialist replacement using supplied/matching cloth.',240,70),
    ('shirt','shirt_darts','Add/remove darts','Refine body suppression with back darts.',60,80),
    ('overcoat','overcoat_sleeve_length','Adjust sleeve length','Shorten/lengthen coat sleeves.',120,10),
    ('overcoat','overcoat_body_suppression','Adjust body','Take in or release coat body.',180,20),
    ('overcoat','overcoat_shorten','Shorten overcoat','Shorten hem and rebalance vent.',300,30),
    ('overcoat','overcoat_shoulders','Adjust shoulders','Narrow or reshape shoulders and reset sleeves.',360,40),
    ('overcoat','overcoat_reline','Full reline','Replace complete coat lining.',480,50),
    ('coat','coat_sleeve_length','Adjust sleeve length','Adjust sleeves on casual outerwear.',120,10),
    ('coat','coat_body_adjust','Adjust body','Take in or release outerwear body.',180,20),
    ('coat','coat_zip_replace','Replace zip','Replace compatible outerwear zip.',180,30),
    ('coat','coat_lining_repair','Lining repair','Repair or replace damaged lining section.',120,40),
    ('formalwear','formal_satin_lapel_repair','Repair satin facings','Specialist repair to satin lapels/facings.',240,10),
    ('formalwear','formal_braid_adjust','Adjust trouser braid','Reset braid after trouser taper/length work.',120,20),
    ('formalwear','formal_morning_tail_balance','Morning coat balance','Correct balance/length of morning coat tails.',300,30),
    ('formalwear','formal_dress_trouser_adjust','Formal trouser adjustment','Adjust evening or morning-dress trousers.',120,40),
    ('denim','denim_original_hem','Original hem','Preserve original washed hem.',75,10),
    ('denim','denim_chainstitch_hem','Chainstitch hem','Specialist chainstitched hem.',60,20),
    ('denim','denim_taper','Taper jeans','Taper leg while respecting felled seams.',120,30),
    ('denim','denim_waist','Adjust waist','Take in waistband and seat.',120,40),
    ('denim','denim_repair','Invisible/reinforced repair','Darn or reinforce worn denim.',120,50),
    ('knitwear','knit_sleeve_length','Adjust knitted sleeves','Specialist shorten/lengthen at cuff or shoulder.',180,10),
    ('knitwear','knit_body_length','Adjust knit body length','Specialist re-linking or hem adjustment.',240,20),
    ('knitwear','knit_repair','Repair knit damage','Re-knit or stabilize holes/pulls.',180,30),
    ('leather','leather_sleeve_length','Adjust leather sleeves','Specialist sleeve shortening.',240,10),
    ('leather','leather_body_adjust','Adjust leather body','Specialist side-seam reshaping.',300,20),
    ('leather','leather_zip_replace','Replace leather garment zip','Specialist zip replacement.',300,30),
    ('leather','leather_lining','Repair/replace lining','Specialist leather garment lining work.',360,40),
    ('accessories','accessory_tie_length','Adjust tie length','Shorten and reconstruct tie.',120,10),
    ('accessories','accessory_belt_length','Adjust belt length','Shorten from buckle end where possible.',90,20),
    ('accessories','accessory_repair','Accessory repair','Custom repair to soft accessory.',90,30),
    ('other','other_custom','Custom alteration','Operation scoped after garment inspection.',120,10),
    ('other','other_repair','Repair','Repair scoped after garment inspection.',120,20)
)
insert into public.alteration_operations (
  category_id, code, name, description, default_duration_minutes, display_order
)
select c.id, o.code, o.name, o.description, o.minutes, o.display_order
from operation o
join public.alteration_catalogue_categories c on c.code = o.category_code;
