-- Seeds the 5 metadata_concept_kind values that had zero canonical
-- concepts (season, garment_type, climate, silhouette, weight_band),
-- plus a matching knowledge_objects card per concept, generated via
-- DeepSeek from a fixed 27-topic list covering each kind's common
-- values. knowledge_topic has no equivalent enum values for these
-- kinds, so each is mapped to the closest existing topic: season ->
-- occasion, garment_type -> styling, climate -> performance,
-- silhouette -> styling, weight_band -> fabric.

INSERT INTO public.metadata_concepts (id, retailer_id, kind, slug, canonical_name, attributes, image_url, active, created_at, updated_at, deleted_at)
VALUES
  ('d8000000-0000-4000-8000-000000000001'::uuid, NULL, 'season'::public.metadata_concept_kind, 'spring-summer-lightweight-tailoring'::text, E'Spring/Summer Lightweight'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000002'::uuid, NULL, 'season'::public.metadata_concept_kind, 'autumn-winter-heavyweight-tailoring'::text, E'Autumn/Winter Heavyweight'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000003'::uuid, NULL, 'season'::public.metadata_concept_kind, 'year-round-transitional-weight'::text, E'Year-round transitional'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000004'::uuid, NULL, 'season'::public.metadata_concept_kind, 'resort-and-warm-climate-wear'::text, E'Resort & Warm Climate'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000005'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'two-piece-suit'::text, E'Two-Piece Suit'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000006'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'three-piece-suit'::text, E'Three-Piece Suit'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000007'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'odd-jacket-sport-coat'::text, E'Odd Jacket / Sport Coat'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000008'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'waistcoat'::text, E'Waistcoat'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000009'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'overcoat'::text, E'Overcoat'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000010'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'trousers'::text, E'Trousers'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000011'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'formal-evening-wear-dinner-jacket-tuxedo'::text, E'Formal Evening Wear'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000012'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'shirt'::text, E'Shirt'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000013'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'knitwear'::text, E'Knitwear'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000014'::uuid, NULL, 'garment_type'::public.metadata_concept_kind, 'shoes'::text, E'Shoes'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000015'::uuid, NULL, 'climate'::public.metadata_concept_kind, 'hot-and-humid-climate'::text, E'Hot & Humid'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000016'::uuid, NULL, 'climate'::public.metadata_concept_kind, 'temperate-four-season-climate'::text, E'Temperate Four-Season'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000017'::uuid, NULL, 'climate'::public.metadata_concept_kind, 'cold-and-dry-climate'::text, E'Cold & Dry'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000018'::uuid, NULL, 'climate'::public.metadata_concept_kind, 'damp-maritime-climate'::text, E'Damp Maritime Climate'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000019'::uuid, NULL, 'silhouette'::public.metadata_concept_kind, 'structured-english-silhouette'::text, E'Structured English'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000020'::uuid, NULL, 'silhouette'::public.metadata_concept_kind, 'soft-neapolitan-silhouette'::text, E'Soft Neapolitan'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000021'::uuid, NULL, 'silhouette'::public.metadata_concept_kind, 'balanced-milanese-silhouette'::text, E'Balanced Milanese'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000022'::uuid, NULL, 'silhouette'::public.metadata_concept_kind, 'modern-slim-silhouette'::text, E'Modern Slim'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000023'::uuid, NULL, 'silhouette'::public.metadata_concept_kind, 'classic-relaxed-silhouette'::text, E'Classic Relaxed'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000024'::uuid, NULL, 'weight_band'::public.metadata_concept_kind, 'tropical-weight-180-220-gsm'::text, E'Tropical Weight'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000025'::uuid, NULL, 'weight_band'::public.metadata_concept_kind, 'lightweight-220-260-gsm'::text, E'Lightweight (220-260 gsm)'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000026'::uuid, NULL, 'weight_band'::public.metadata_concept_kind, 'mid-weight-260-320-gsm'::text, E'Mid-weight (260-320 gsm)'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL),
  ('d8000000-0000-4000-8000-000000000027'::uuid, NULL, 'weight_band'::public.metadata_concept_kind, 'heavyweight-320-plus-gsm'::text, E'Heavyweight (320+ gsm)'::text, '{}'::jsonb, NULL::text, true::boolean, now(), now(), NULL)
ON CONFLICT (kind, slug) WHERE retailer_id IS NULL DO UPDATE SET
  canonical_name = excluded.canonical_name,
  updated_at = now(),
  deleted_at = null;

INSERT INTO public.knowledge_objects (id, retailer_id, topic, title, slug, summary, body, image_url, display_types, commercial_intent, priority, active, created_at, updated_at, deleted_at)
VALUES
  ('d7000000-0000-4000-8000-000000000001'::uuid, NULL, 'occasion'::public.knowledge_topic, E'Mastering Warm-Weather Tailoring with Breathable Fabrics'::text, 'mastering-warm-weather-tailoring-with-breathable-fabrics'::text, E'Discover how lightweight wool, linen, and high-twist fabrics keep you cool while maintaining sharp silhouettes in warmer months.'::text, E'Spring and summer demand tailored clothing that balances comfort with structure. Lightweight wool (200-240g) breathes naturally while resisting wrinkles, making it ideal for business attire. High-twist worsteds like Fresco offer durability with exceptional airflow, while linen provides unmatched breathability for casual jackets and trousers.

For tropical climates, consider unlined or half-lined constructions in open-weave fabrics. Seersucker and cotton-silk blends work well for sport coats, maintaining shape without trapping heat. Proper garment care—including steam pressing rather than ironing delicate linens—preserves your warm-weather wardrobe''s crispness season after season.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000002'::uuid, NULL, 'occasion'::public.knowledge_topic, E'Mastering Cold-Weather Tailoring with Heavyweight Fabrics'::text, 'mastering-cold-weather-tailoring-with-heavyweight-fabrics'::text, E'Explore how heavyweight wool and structured silhouettes provide warmth and elegance during autumn and winter months.'::text, E'Autumn and winter demand tailoring that balances insulation with sophistication. Heavyweight wool (18oz+) is the cornerstone, offering natural temperature regulation and durability. Flannel, tweed, and cashmere blends add texture while maintaining a polished look. Structured silhouettes with slightly roomier cuts accommodate layering without compromising shape.

Consider double-breasted coats, thick-lined trousers, and layered waistcoats for practical elegance. Darker hues like charcoal, navy, and forest green align with seasonal palettes while hiding wear. These pieces transition seamlessly from office to evening events, making them versatile investments. Proper storage with cedar hangers prevents moth damage during offseason months.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000003'::uuid, NULL, 'occasion'::public.knowledge_topic, E'Mastering year-round transitional tailoring'::text, 'mastering-year-round-transitional-tailoring'::text, E'Versatile weight bands bridge seasons with comfort, maintaining sharp silhouettes through temperature shifts.'::text, E'Year-round transitional weights are the unsung heroes of a polished wardrobe, offering 3-4 season versatility without sacrificing structure. These medium-weight fabrics (280-320g) balance breathability and warmth, engineered for smooth layering in spring breezes or autumn chills. Wool blends with silk or linen often excel here, resisting wrinkles while adapting to your body''s microclimate.

Savvy dressers lean on transitional pieces to maximize cost-per-wear across climates. A well-chosen fresco wool suit, for instance, works for air-conditioned summers and mild winters alike. These fabrics answer the modern need for wardrobe efficiency, proving premium menswear needn''t be seasonal. Proper rotation and care ensure these pieces remain cornerstone items for years.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000004'::uuid, NULL, 'occasion'::public.knowledge_topic, E'Mastering Hot Weather Tailoring Essentials'::text, 'mastering-hot-weather-tailoring-essentials'::text, E'How to dress sharply without compromising comfort in tropical destinations or summer months through fabric choices and construction techniques.'::text, E'Resort wear and warm-climate tailoring demand a strategic approach to balance elegance with practicality. The key lies in selecting breathable natural fibers like linen, tropical wool, and high-twist cottons that allow air circulation while maintaining structure. Lighter canvas constructions and half-lined jackets provide ventilation where traditional tailoring would overwhelm.

Silhouettes should be slightly relaxed with shorter jacket lengths for better airflow. Neutral and stone color palettes reflect sunlight while remaining versatile. Consider unlined sport coats, fresco weaves that resist wrinkles, and accessories like panama hats for complete climate-appropriate dressing. These techniques let you maintain sartorial standards even when temperatures soar.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000005'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Versatile Foundation of Menswear'::text, 'the-versatile-foundation-of-menswear'::text, E'A tailored two-piece suit combines timeless elegance with modern versatility, adapting seamlessly from business to formal occasions.'::text, E'The two-piece suit, comprising a jacket and matching trousers, is the cornerstone of a gentleman''s wardrobe. Its balanced structure flatters most body types while offering endless styling possibilities through fabric choices, lapel styles, and subtle detailing. A well-fitted suit elevates posture, projects confidence, and serves as a blank canvas for personal expression through accessories and shirt pairings.

Modern tailoring techniques have made suits more comfortable than ever, with lightweight canvassing and stretch fabrics maintaining shape without restricting movement. Whether in classic navy wool for boardrooms or linen for summer weddings, a quality suit remains the most versatile investment in menswear. Proper maintenance ensures a decade-long lifespan, making cost-per-wear exceptionally favorable compared to fast fashion alternatives.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000006'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Pinnacle of Tailored Sophistication'::text, 'the-pinnacle-of-tailored-sophistication'::text, E'A three-piece suit elevates business and formal attire with its structured elegance, perfect for impactful impressions.'::text, E'The three-piece suit represents the zenith of menswear tailoring, combining a jacket, trousers, and matching waistcoat for unrivaled formality and cohesion. Ideal for weddings, high-stakes meetings, or commanding presence, its layered composition ensures superior drape and temperature regulation. The waistcoat adds dimensionality while concealing shirt-tucking imperfections, creating flawless lines.

Modern iterations balance tradition with contemporary fits—slimmer cuts through the torso and tapered trousers refresh this classic. Luxury fabrics like Super 120s wool or silk-blend fresco offer year-round versatility. Careful proportioning of waistcoat length (covering the trouser waistband) and jacket coverage prevents bulk. As an investment piece, it outperforms separates in cost-per-wear for frequent formalwear needs.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000007'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Versatile Odd Jacket Staple'::text, 'the-versatile-odd-jacket-staple'::text, E'A sport coat bridges tailored polish and relaxed versatility, perfect for smart-casual elevation.'::text, E'The odd jacket (or sport coat) is the Swiss Army knife of tailored menswear - more structured than a blazer yet less formal than a suit jacket. Originally designed for country sports with features like patch pockets and rugged fabrics, it''s evolved into a wardrobe workhorse that pairs equally well with dress trousers, denim, or odd waistcoats.

Unlike suit jackets, odd jackets are meant to stand alone, showcasing bolder patterns, textured tweeds, or seasonal linen. Ideal for cocktail attire, creative offices, or weekend wear, they strike the perfect balance between polish and personality. The best versions feature natural shoulders, a 3-roll-2 button stance, and enough drape to move comfortably.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000008'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Versatile Waistcoat: Formal to Casual'::text, 'the-versatile-waistcoat-formal-to-casual'::text, E'A waistcoat adds polish to suits or stands alone as a sharp layering piece, blending formality with personal style.'::text, E'The waistcoat, a sleeveless garment worn over a shirt and under a suit jacket, elevates tailoring with structure and versatility. Originally a practical layer in 17th-century Europe, it now balances tradition and modernity—perfect for three-piece suits or paired with separates. Key features include adjustable back straps, varied lapel styles (notch, peak, or shawl), and fabrics ranging from wool to linen.

Contemporary styling breaks rules: try a textured waistcoat with denim for smart-casual flair, or a double-breasted cut for bold formality. Proper fit is critical—snug but not restrictive, with the bottom covering the trouser waistband. For summer, unlined cotton or seersucker options maintain elegance without overheating.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000009'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Timeless Elegance of Overcoats'::text, 'the-timeless-elegance-of-overcoats'::text, E'A guide to selecting and styling overcoats for maximum versatility and enduring sophistication in menswear.'::text, E'The overcoat is a cornerstone of refined outerwear, designed to be worn over suits or tailored separates in colder months. Its extended length (typically knee-to-calf) provides superior warmth while maintaining a sharp silhouette. Classic styles like the polo coat or chesterfield offer distinct aesthetic personalities through details such as raglan sleeves, velvet collars, or covert cloth construction.

Quality overcoats balance substantial wool fabrics (24-32oz) with precise tailoring to avoid bulkiness. Neutral colors like charcoal or camel transition effortlessly between formal and casual contexts. Modern iterations incorporate technical fabrics for weather resistance without compromising the garment''s elegant drape. Proper storage on broad hangers preserves the coat''s structure between seasons.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000010'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Art of Choosing Tailored Trousers'::text, 'the-art-of-choosing-tailored-trousers'::text, E'Discover how the right trousers balance comfort, style, and versatility for any occasion.'::text, E'Trousers are the foundation of a polished wardrobe, offering endless possibilities for both formal and casual ensembles. A well-fitted pair enhances your silhouette, providing comfort without sacrificing sophistication. The choice of fabric, cut, and detailing determines their suitability for different settings, from office wear to weekend outings.

Investing in quality trousers means prioritizing durability and timeless design. Wool and cotton blends offer breathability and structure, while subtle patterns or textures add personality. Consider pleats, cuffs, and waistband styles to align with your aesthetic. Proper tailoring ensures they drape elegantly, creating a seamless transition between jackets or knitwear.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000011'::uuid, NULL, 'styling'::public.knowledge_topic, E'Mastering Black Tie: The Dinner Jacket Code'::text, 'mastering-black-tie-the-dinner-jacket-code'::text, E'Tuxedos define formal elegance with timeless silhouettes and luxurious fabrics, requiring exacting details for proper black-tie occasions.'::text, E'The dinner jacket, or tuxedo, represents the pinnacle of men''s formalwear with its satin lapels, jetted pockets, and single-button closure. Traditionally in midnight blue or black, it demands matching trousers with a silk braid stripe and patent leather shoes. A crisp white dress shirt with pleated front and onyx studs completes the foundation.

Modern interpretations allow for subtle personalization through shawl collar variations, cummerbund fabrics, or discreet patterned bow ties. While black-tie events strictly require this ensemble, contemporary styling now permits midnight blue alternatives or tasteful textural contrasts in winter. Proper fit remains non-negotiable - the jacket should skim the body with precise shoulder alignment and trouser breaks.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000012'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Versatile Foundation of Menswear'::text, 'the-versatile-foundation-of-menswear-2'::text, E'Shirts bridge casual and formal, offering endless styling possibilities with careful fabric and fit selection.'::text, E'A well-chosen shirt serves as the cornerstone of a man''s wardrobe, transitioning effortlessly from office wear to weekend casual. The key lies in understanding collar styles, fabric weights, and weaves—oxford for durability, poplin for crispness, or linen for breathability.

Beyond basics, consider subtle details like placket styles, cuff designs, and yoke construction that elevate a shirt''s character. Proper collar roll and sleeve length ensure polish, while untucked hems create intentional relaxation. Modern tailoring increasingly blurs formal/casual boundaries through innovative fabric blends and construction techniques.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000013'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Versatile World of Knitwear'::text, 'the-versatile-world-of-knitwear'::text, E'Explore knitwear''s balance of comfort and sophistication, from casual sweaters to refined cashmere layers.'::text, E'Knitwear encompasses a range of garments crafted from interlocking yarns, offering both warmth and breathability. From chunky cable-knit sweaters for weekend wear to fine-gauge merino wool for office-appropriate layers, the category balances rugged durability with refined elegance.

Quality knitwear distinguishes itself through fiber selection (cashmere, lambswool, or technical blends) and construction techniques like fully fashioned seams. Proper care involves gentle washing, flat drying, and seasonal storage to maintain shape and longevity. The best pieces become wardrobe staples that develop character over time.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000014'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Foundation of a Polished Look'::text, 'the-foundation-of-a-polished-look'::text, E'Elevate your ensemble with expertly crafted shoes, blending comfort, durability, and timeless style.'::text, E'Shoes are more than just functional footwear; they anchor your entire outfit and communicate your attention to detail. A well-chosen pair balances comfort for all-day wear with refined aesthetics, whether opting for classic Oxfords, versatile loafers, or sleek Chelsea boots. Quality materials like full-grain leather and Goodyear welting ensure longevity, making them a worthwhile investment.

Consider pairing shoes with your wardrobe''s dominant tones and occasions. Dark brown or black leather works for formal settings, while suede or textured finishes add casual sophistication. Proper care—regular polishing, shoe trees, and rotation—extends their lifespan and maintains their sharp appearance. The right shoes seamlessly bridge practicality and sartorial elegance.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000015'::uuid, NULL, 'performance'::public.knowledge_topic, E'Dressing Smart in Sweltering Humidity'::text, 'dressing-smart-in-sweltering-humidity'::text, E'Learn how breathable fabrics and relaxed tailoring combat discomfort while maintaining sharp style in tropical climates.'::text, E'Hot and humid climates demand strategic fabric choices and construction to prevent overheating while retaining polish. Opt for open-weave wools like fresco or high-twist tropical wool, which wick moisture and resist wrinkling. Linen and cotton-linen blends offer unmatched breathability, though require acceptance of natural crumpling. Unlined or half-lined jackets with minimal shoulder padding improve airflow without sacrificing structure.

Silhouettes should prioritize ventilation: consider patch pockets over flaps, shorter jacket lengths, and higher armholes. Lightweight trousers in fresco wool or cotton-linen blends pair well with unstructured jackets for a complete breathable ensemble. Avoid synthetic blends that trap heat, and embrace lighter mid-gray or tan hues that reflect sunlight while maintaining formality.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000016'::uuid, NULL, 'performance'::public.knowledge_topic, E'Dressing Smart in Changing Temperate Climates'::text, 'dressing-smart-in-changing-temperate-climates'::text, E'Master year-round elegance with layered tailoring that adapts seamlessly between seasons.'::text, E'Temperate four-season climates demand a versatile wardrobe that transitions smoothly between warm summers, crisp autumns, chilly winters, and mild springs. The key lies in breathable mid-weight fabrics with natural temperature regulation like wool flannels and high-twist worsteds, complemented by strategic layering pieces that add or subtract warmth as needed.

Invest in convertible elements like zip-out linings, adjustable vents, and removable collars to extend your garments'' seasonal range. A core suit rotation in navy, charcoal, and medium gray provides maximum coordination potential across all seasons, while seasonal accent pieces like lightweight summer blazers or heavier winter topcoats ensure you''re always appropriately dressed. Focus on medium-weight (250-300g) year-round fabrics for your foundation pieces, then supplement with seasonal outliers to cover temperature extremes.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000017'::uuid, NULL, 'performance'::public.knowledge_topic, E'Mastering Winter Style in Arid Climates'::text, 'mastering-winter-style-in-arid-climates'::text, E'Tailoring strategies for staying sharp and comfortable when temperatures drop and humidity vanishes.'::text, E'Dressing for cold, dry climates demands a focus on both insulation and breathability. Wool flannels and tweeds provide natural warmth without trapping moisture, while layered mid-weight garments allow temperature regulation. Desert winters particularly benefit from unlined jackets and open-weave knits that prevent overheating during temperature swings.

Pay special attention to fabric choices - cashmere overcoats and merino base layers combat wind chill without bulk. Avoid synthetics that exacerbate static in low humidity. Accessories like lined leather gloves and lightweight scarves add practical warmth while maintaining a polished look. Remember: dryness accelerates fabric wear, so invest in quality fibers that withstand abrasive conditions.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000018'::uuid, NULL, 'performance'::public.knowledge_topic, E'Dressing for Coastal Dampness and Breezes'::text, 'dressing-for-coastal-dampness-and-breezes'::text, E'Master tailored layering and fabric choices to stay sharp in humid, salt-air environments without sacrificing comfort.'::text, E'Coastal climates with persistent dampness and salty breezes demand menswear that balances breathability with protection. Opt for loosely woven wool blends like fresco or high-twist worsteds, which resist moisture absorption while allowing air circulation. Unlined or half-lined jackets prevent cling, while rust-proof horn or corozo buttons maintain polish.

Layer with moisture-wicking performance knits beneath your tailored pieces for transitional warmth. Trousers in compact cotton-linen blends dry quickly and resist salt stains. Finish with weatherproofed leather footwear and avoid uncoated suede, which discolors in humid air. These fabric and construction choices ensure your wardrobe withstands maritime conditions while maintaining a crisp silhouette.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000019'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Timeless Appeal of Structured English Tailoring'::text, 'the-timeless-appeal-of-structured-english-tailoring'::text, E'Defined by sharp shoulders and a military-inspired torso, this silhouette exudes authority with intentional formality.'::text, E'The Structured English silhouette emerged from Savile Row''s military tailoring heritage, featuring pronounced roping at the shoulder heads and a clean, suppressed waist. This creates a commanding ''V'' shape that enhances posture while maintaining wearability through precise canvas construction.

Modern interpretations balance traditional structure with contemporary comfort, using lighter wools and reduced padding. Ideal for boardroom wear or formal occasions, this silhouette works particularly well for athletic builds seeking definition, though skilled tailors can adapt it to most body types through precise darting and balance adjustments.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000020'::uuid, NULL, 'styling'::public.knowledge_topic, E'Effortless Elegance: The Soft Neapolitan Silhouette'::text, 'effortless-elegance-the-soft-neapolitan-silhouette'::text, E'A relaxed yet refined Italian tailoring style with natural shoulders and light construction for modern comfort.'::text, E'The Soft Neapolitan silhouette reimagines traditional Italian tailoring through a contemporary lens. Characterized by its unpadded, gently sloping shoulders and minimal canvas construction, this style prioritizes comfort without sacrificing sophistication. The jacket''s shorter length and slightly suppressed waist create a flattering profile that moves naturally with the body.

Originating from Naples'' warm climate, the style features features like patch pockets, a 3-roll-2 button stance, and spalla camicia (shirt shoulder) construction. Unlike stiffer British suits, these jackets are designed to drape rather than structure, making them ideal for both business casual settings and warm-weather elegance. The lightweight wools and open weaves commonly used further enhance breathability and year-round versatility.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000021'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Art of Balanced Milanese Tailoring'::text, 'the-art-of-balanced-milanese-tailoring'::text, E'A harmonious silhouette blending soft Neapolitan comfort with structured Milanese precision for versatile elegance.'::text, E'The balanced Milanese silhouette strikes a masterful compromise between contrasting tailoring traditions. It retains the relaxed shoulders and lightweight construction of Neapolitan style while incorporating Milanese precision through subtle waist suppression and cleaner lines.

This hybrid approach creates exceptional versatility, offering enough structure for professional settings without sacrificing comfort. The silhouette works particularly well for travelers and those seeking one suit that transitions effortlessly from office to evening. Jackets typically feature a medium lapel width and slightly extended shoulders to maintain proportionality.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000022'::uuid, NULL, 'styling'::public.knowledge_topic, E'The Contemporary Appeal of Slim Tailoring'::text, 'the-contemporary-appeal-of-slim-tailoring'::text, E'Slim silhouettes offer a sleek, body-conscious cut that balances structure with modern comfort for a polished yet approachable look.'::text, E'The modern slim silhouette redefines classic tailoring with narrower lapels, higher armholes, and a tapered waist for a streamlined profile. This cut reduces excess fabric while maintaining movement, ideal for those seeking sharpness without stiffness. Its versatility bridges formal and casual settings, adapting to both suits and sport coats.

Rooted in contemporary preferences, the slim silhouette flatters athletic builds but can be adjusted for various body types through precise tailoring. Designers often pair it with lightweight wool or stretch blends to enhance comfort. While trend-driven, its clean lines ensure longevity beyond seasonal cycles, making it a strategic investment for the style-conscious wardrobe.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000023'::uuid, NULL, 'styling'::public.knowledge_topic, E'Effortless tailoring with room to breathe'::text, 'effortless-tailoring-with-room-to-breathe'::text, E'The classic relaxed silhouette balances structure and comfort for timeless menswear that moves with you.'::text, E'A hallmark of refined casualwear, the classic relaxed silhouette offers subtle tailoring with intentionally generous proportions. Jackets feature slightly extended shoulders and a gently tapered waist, while trousers have a mid-rise with a straight leg that drapes cleanly. This approach maintains sophistication while prioritizing all-day comfort.

Ideal for business casual or weekend wear, the silhouette works exceptionally well in unstructured fabrics like hopsack wool or cotton-linen blends. It pairs effortlessly with softer shoulder constructions and unlined designs for a natural drape. The look bridges formal and informal settings, offering versatility without sacrificing polish—perfect for men who value both aesthetics and ease of movement.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'educate'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000024'::uuid, NULL, 'fabric'::public.knowledge_topic, E'Mastering Lightweight Tailoring with Tropical Wool'::text, 'mastering-lightweight-tailoring-with-tropical-wool'::text, E'Tropical weight wools (180-220 gsm) offer breathable elegance for warm climates without sacrificing structure or drape.'::text, E'Tropical weight fabrics strike the perfect balance for warm-weather tailoring. At 180-220 grams per square meter (gsm), these wools provide exceptional breathability while maintaining enough body to hold a sharp silhouette. The open weave allows air circulation, making them ideal for summer suits or year-round wear in tropical climates.

Despite their lightweight nature, tropical wools resist wrinkling better than linen or cotton alternatives. They''re often blended with silk or mohair for added luster and durability. This weight band works particularly well for unstructured jackets, travel suits, and business attire in warmer offices. When properly cared for, tropical wool garments can transition effortlessly from daytime meetings to evening events.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000025'::uuid, NULL, 'fabric'::public.knowledge_topic, E'The Tailored Comfort of Lightweight Fabrics'::text, 'the-tailored-comfort-of-lightweight-fabrics'::text, E'Premium suiting in 220-260gsm offers breathable elegance for warmer climates without sacrificing structure.'::text, E'Lightweight fabrics between 220-260gsm strike the perfect balance for warm-weather tailoring. These cloths maintain enough body for clean drape and silhouette definition while allowing exceptional breathability. Ideal for tropical wool suits or high-twist fresco collections, this weight handles summer heat with dignified composure.

Modern looms produce remarkable 240gsm wools that resist wrinkling better than heavier alternatives. Our curated lightweight selections source superfine merino yarns with open weaves for natural climate control. When layered with half-lined construction, this creates suits that transition effortlessly from boardroom to garden party while maintaining professional polish.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000026'::uuid, NULL, 'fabric'::public.knowledge_topic, E'The Versatile Mid-Weight Wool Sweet Spot'::text, 'the-versatile-mid-weight-wool-sweet-spot'::text, E'Discover why 260-320 gsm wools balance year-round comfort with structure for business and smart casual tailoring.'::text, E'Mid-weight wool fabrics between 260-320 gsm (grams per square meter) hit the sweet spot for versatile menswear. These cloths maintain enough structure for crisp suit jackets and trousers while remaining breathable for extended wear. The density provides wrinkle resistance during travel without feeling heavy against the skin.

This weight band transitions seamlessly across seasons in most climates, making it a workhorse for business wardrobes. Millesimer-quality mid-weights drape beautifully while offering durability for daily office wear. Savvy dressers often build capsule wardrobes around these adaptable fabrics complemented by lighter or heavier pieces as needed.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'upgrade'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL),
  ('d7000000-0000-4000-8000-000000000027'::uuid, NULL, 'fabric'::public.knowledge_topic, E'The Strength of Heavyweight Tailoring'::text, 'the-strength-of-heavyweight-tailoring'::text, E'Heavyweight fabrics (320+ gsm) offer unmatched durability, structure, and year-round versatility for discerning gentlemen.'::text, E'Heavyweight fabrics, defined as 320 grams per square meter (gsm) or above, are the cornerstone of enduring menswear. These dense woolens or tweeds provide exceptional drape, resist wrinkling, and maintain their shape through years of wear. Ideal for structured garments like overcoats, winter suits, and durable trousers, they convey authority through substantial handfeel.

While often associated with colder climates, modern heavyweight weaves incorporate breathability for three-season versatility. Their inherent insulation works equally well in crisp autumn air or air-conditioned boardrooms. For investment pieces meant to last decades, heavyweight fabrics justify their premium through longevity – often outliving their owners with proper care.'::text, NULL::text, ARRAY['information_card','accordion']::public.knowledge_display_type[], 'justify_premium'::public.knowledge_commercial_intent, 0::integer, true::boolean, now(), now(), NULL)
ON CONFLICT (slug) WHERE retailer_id IS NULL DO UPDATE SET
  summary = excluded.summary,
  body = excluded.body,
  updated_at = now(),
  deleted_at = null;

INSERT INTO public.knowledge_object_concepts (id, knowledge_object_id, concept_id, match_strength, created_at, updated_at, deleted_at)
VALUES
  ('d9000000-0000-4000-8000-000000000001'::uuid, 'd7000000-0000-4000-8000-000000000001'::uuid, 'd8000000-0000-4000-8000-000000000001'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000002'::uuid, 'd7000000-0000-4000-8000-000000000002'::uuid, 'd8000000-0000-4000-8000-000000000002'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000003'::uuid, 'd7000000-0000-4000-8000-000000000003'::uuid, 'd8000000-0000-4000-8000-000000000003'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000004'::uuid, 'd7000000-0000-4000-8000-000000000004'::uuid, 'd8000000-0000-4000-8000-000000000004'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000005'::uuid, 'd7000000-0000-4000-8000-000000000005'::uuid, 'd8000000-0000-4000-8000-000000000005'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000006'::uuid, 'd7000000-0000-4000-8000-000000000006'::uuid, 'd8000000-0000-4000-8000-000000000006'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000007'::uuid, 'd7000000-0000-4000-8000-000000000007'::uuid, 'd8000000-0000-4000-8000-000000000007'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000008'::uuid, 'd7000000-0000-4000-8000-000000000008'::uuid, 'd8000000-0000-4000-8000-000000000008'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000009'::uuid, 'd7000000-0000-4000-8000-000000000009'::uuid, 'd8000000-0000-4000-8000-000000000009'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000010'::uuid, 'd7000000-0000-4000-8000-000000000010'::uuid, 'd8000000-0000-4000-8000-000000000010'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000011'::uuid, 'd7000000-0000-4000-8000-000000000011'::uuid, 'd8000000-0000-4000-8000-000000000011'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000012'::uuid, 'd7000000-0000-4000-8000-000000000012'::uuid, 'd8000000-0000-4000-8000-000000000012'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000013'::uuid, 'd7000000-0000-4000-8000-000000000013'::uuid, 'd8000000-0000-4000-8000-000000000013'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000014'::uuid, 'd7000000-0000-4000-8000-000000000014'::uuid, 'd8000000-0000-4000-8000-000000000014'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000015'::uuid, 'd7000000-0000-4000-8000-000000000015'::uuid, 'd8000000-0000-4000-8000-000000000015'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000016'::uuid, 'd7000000-0000-4000-8000-000000000016'::uuid, 'd8000000-0000-4000-8000-000000000016'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000017'::uuid, 'd7000000-0000-4000-8000-000000000017'::uuid, 'd8000000-0000-4000-8000-000000000017'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000018'::uuid, 'd7000000-0000-4000-8000-000000000018'::uuid, 'd8000000-0000-4000-8000-000000000018'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000019'::uuid, 'd7000000-0000-4000-8000-000000000019'::uuid, 'd8000000-0000-4000-8000-000000000019'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000020'::uuid, 'd7000000-0000-4000-8000-000000000020'::uuid, 'd8000000-0000-4000-8000-000000000020'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000021'::uuid, 'd7000000-0000-4000-8000-000000000021'::uuid, 'd8000000-0000-4000-8000-000000000021'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000022'::uuid, 'd7000000-0000-4000-8000-000000000022'::uuid, 'd8000000-0000-4000-8000-000000000022'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000023'::uuid, 'd7000000-0000-4000-8000-000000000023'::uuid, 'd8000000-0000-4000-8000-000000000023'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000024'::uuid, 'd7000000-0000-4000-8000-000000000024'::uuid, 'd8000000-0000-4000-8000-000000000024'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000025'::uuid, 'd7000000-0000-4000-8000-000000000025'::uuid, 'd8000000-0000-4000-8000-000000000025'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000026'::uuid, 'd7000000-0000-4000-8000-000000000026'::uuid, 'd8000000-0000-4000-8000-000000000026'::uuid, 1::numeric, now(), now(), NULL),
  ('d9000000-0000-4000-8000-000000000027'::uuid, 'd7000000-0000-4000-8000-000000000027'::uuid, 'd8000000-0000-4000-8000-000000000027'::uuid, 1::numeric, now(), now(), NULL)
ON CONFLICT (knowledge_object_id, concept_id) WHERE deleted_at IS NULL DO NOTHING;
